### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mayank1897**

### CODE REVIEW

**Review by JacobMGEvans — APPROVED** [review]
Considering line 136 is using a period and these are proper sentences I would tend to agree with this change. Thank you @mayank1897

**Comment by mayank1897** [comment]
try to merge it.

**Comment by JacobMGEvans** [comment]
> try to merge it.

That is ultimately up to Kent

**Comment by therealklanni** [comment]
Hacktober spam

**Comment by mayank1897** [comment]
changing the README.md for better readability.....it's not a Hacktober spam!!

**Comment by kentcdodds** [comment]
Thanks for the contribution. I believe you made it in good faith, but I disagree that this is an improvement so I won't be merging it. Thanks anyway :)

**Comment by JacobMGEvans** [comment]
> changing the README.md for better readability.....it's not a Hacktober spam!!

It was worth a shot. Hope you find other things to improve 😄

**Pull request closed without merging**
