### PR TITLE
telescope favicon

### PR DESCRIPTION
**Pull request by Aprillion**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks! Could we do this one instead?

04-advanced-react-patterns

**Comment by Aprillion** [comment]
> Thanks! Could we do this one instead?

Oh, I had a feeling I was missing something when doing the Friday night commits 🤦‍♂️
I will update all my PRs, thanks for the feedback!

**Comment by Aprillion** [comment]
Ufff, all PRs updated and double checked (fun fact: amending commits is much more fun when you have write access).
Here is a script to tripple check them all after merging...

```js
`react-fundamentals
react-hooks
advanced-react-hooks
advanced-react-patterns
react-performance
react-suspense
testing-react-apps`.split('\n').forEach(repo => open(`https://raw.githubusercontent.com/kentcdodds/${repo}/main/public/favicon.ico`))
```

image

**Comment by kentcdodds** [comment]
@all-contributors please add @Aprillion for code

**Pull request merged**
