### PR TITLE
Small comment typo in 03.js

### PR DESCRIPTION
**Pull request by emzoumpo**
Fix `implicitely` -> `implicitly`

### CODE REVIEW

**Review by kentcdodds — APPROVED** [review]
Thank you!

**Comment by kentcdodds** [comment]
@all-contributors please add @emzoumpo for docs

**Comment by kentcdodds** [comment]
@emzoumpo, I think you've contributed to almost every one of the repositories! Thank you so much!

**Comment by emzoumpo** [comment]
@kentcdodds first of all thank you so much for putting in the effort to put out so much world class, quality content for us out there! 👏
Your Epic React course is really something else, and I'm very happy to help out where I can (even in small chunks).
I hope my PRs were not overwhelming, just thought I would quickly go through all the repos and see whether I could fix something.

**Comment by kentcdodds** [comment]
It was excellent! Thank you!

--- original message ---
On Fri, Oct 2 at 06:30 PM, <notifications@github.com> Emmanouil Zoumpoulakis wrote:



@kentcdodds first of all thank you so much for putting in the effort to put out so much world class, quality content for us out there! 👏

Your Epic React course is really something else, and I'm very happy to help out where I can (even in small chunks).

I hope my PRs were not overwhelming, just thought I would quickly go through all the repos and see whether I could fix something.

—

You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
--- end of original message ---

**Pull request merged**
